name: Database Changes Notification

on:
  push:
    branches:
      - 'release/**'
    paths:
      - '**/src/main/resources/db/**'
  workflow_dispatch: {}
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest release
        id: get_latest_release
        uses: actions/github-script@v7
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            const latestRelease = releases.data[0]?.tag_name || '';
            core.setOutput('latest_release', latestRelease);

      - name: Get changed files
        id: get_changes
        run: |
          if [ -n "${{ steps.get_latest_release.outputs.latest_release }}" ]; then
            CHANGED_FILES=$(git diff --name-only ${{ steps.get_latest_release.outputs.latest_release }} HEAD -- "**/src/main/resources/db/**")
          else
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- "**/src/main/resources/db/**")
          fi
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Add changes to workflow summary
        run: |
          echo "## Database Changes Detected" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Changed Files:" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.get_changes.outputs.changed_files }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Comparison Link:" >> $GITHUB_STEP_SUMMARY
          echo "[View changes](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/compare/${{ steps.get_latest_release.outputs.latest_release }}...${GITHUB_SHA})" >> $GITHUB_STEP_SUMMARY 